#variable access_key {}
#variable secret_key {}
variable region {}
variable instance {}
variable ami {}
variable associate_public_ip_address {}
variable subnet_id {}
variable sec1_id {}
variable private_key_path {}
variable username {}
variable keypair {}
variable value {}
